import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Navbar from '@/src/components/Navbar';
import AuthContext from '@/src/context/AuthContext';
import SWRConfigContext from '@/src/context/SWRContext';

const openSans = Open_Sans({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AuthContext>
        <Navbar />

        <SWRConfigContext>
          <html lang="en" className={`${openSans.variable} antialiased`}>
            <body className="w-full max-w-screen-xl overflow-auto mx-auto">
              <main className="w-full flex justify-center bg-amber-50 min-h-full">
                {children}
              </main>
            </body>
          </html>
        </SWRConfigContext>
      </AuthContext>
    </>
  );
}
